name: Build and Test
on:
  push:
    branches:
      - "main"
      - "release-v*"
    paths-ignore:
      - "**/*.png"
  pull_request:
    branches:
      - "main"
      - "release-v*"
    paths-ignore:
      - "**/*.png"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ci/actions/setup-deps

      - run: make -k lint
        env:
          MAKE_IN_DOCKER: "1"

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ci/actions/setup-deps

      # build
      - run: make docker-build

      # test
      - run: go test ./... -race -coverprofile=coverage.xml -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          name: codecov-envoy-gateway
          verbose: true

      # push
      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: make docker-push
        if: github.event_name == 'push'
      - name: Push to :latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag "docker.io/envoyproxy/gateway-dev:$(git rev-parse --short HEAD)" docker.io/envoyproxy/gateway-dev:latest
          docker push docker.io/envoyproxy/gateway-dev:latest
